import nodemailer from 'nodemailer';
import { env } from '../config/env.js';
import { logger } from '../observability/logger.js';
import type { Job } from '../db/schema.js';

const log = logger.child({ module: 'export:email' });

function ensureEmailConfigured(): void {
  if (!env.SMTP_HOST || !env.SMTP_USER || !env.SMTP_PASS || !env.EMAIL_TO) {
    throw new Error(
      'Email is not configured. Set SMTP_HOST, SMTP_USER, SMTP_PASS, and EMAIL_TO in .env',
    );
  }
}

export function isEmailConfigured(): boolean {
  return !!(env.SMTP_HOST && env.SMTP_USER && env.SMTP_PASS && env.EMAIL_TO);
}

function buildJobTableHtml(jobs: Job[]): string {
  const rows = jobs.map(job => `
    <tr>
      <td style="padding:8px;border:1px solid #ddd"><a href="${job.link}">${job.title}</a></td>
      <td style="padding:8px;border:1px solid #ddd">${job.company}</td>
      <td style="padding:8px;border:1px solid #ddd;text-align:center">${job.score ?? '0'}/10</td>
      <td style="padding:8px;border:1px solid #ddd">${job.seniority ?? '-'}</td>
      <td style="padding:8px;border:1px solid #ddd">${job.summary ?? '-'}</td>
    </tr>
  `).join('');

  return `
    <div style="font-family:Arial,sans-serif;max-width:900px;margin:0 auto">
      <h2 style="color:#333">Job Hunter Summary</h2>
      <p style="color:#666">${jobs.length} jobs exported on ${new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}</p>
      <table style="width:100%;border-collapse:collapse;margin-top:16px">
        <thead>
          <tr style="background:#f5f5f5">
            <th style="padding:8px;border:1px solid #ddd;text-align:left">Title</th>
            <th style="padding:8px;border:1px solid #ddd;text-align:left">Company</th>
            <th style="padding:8px;border:1px solid #ddd;text-align:center">Score</th>
            <th style="padding:8px;border:1px solid #ddd;text-align:left">Seniority</th>
            <th style="padding:8px;border:1px solid #ddd;text-align:left">Summary</th>
          </tr>
        </thead>
        <tbody>${rows}</tbody>
      </table>
      <p style="color:#999;font-size:12px;margin-top:16px">Generated by Job Hunter at ${new Date().toISOString()}</p>
    </div>
  `;
}

export async function sendJobSummaryEmail(jobs: Job[]): Promise<void> {
  ensureEmailConfigured();

  const transporter = nodemailer.createTransport({
    host: env.SMTP_HOST,
    port: 587,
    secure: false,
    auth: {
      user: env.SMTP_USER,
      pass: env.SMTP_PASS,
    },
  });

  const date = new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });

  await transporter.sendMail({
    from: env.SMTP_USER,
    to: env.EMAIL_TO,
    subject: `Job Hunter Summary — ${date} — ${jobs.length} jobs`,
    html: buildJobTableHtml(jobs),
  });

  log.info({ count: jobs.length, to: env.EMAIL_TO }, 'Sent job summary email');
}
